version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - VECTOR_DB_TYPE=${VECTOR_DB_TYPE:-postgres}
    volumes:
      - huggingface-cache:/root/.cache/huggingface
      - ./data:/app/data  # Mount data directory (PDFs and embeddings)
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 16G

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  huggingface-cache: